services:
  ml-model:
    image: ghcr.io/devhub-p2a/devhub-fleet-booking-ml:latest
    container_name: ml-model
    restart: unless-stopped
    ports:
      - "8000:8000"

  mvc-app:
    image: ghcr.io/devhub-p2a/devhub-fleet-booking-mvc:latest
    container_name: mvc-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - ml-model